### ISSUE TITLE
Cute fork :)

### ISSUE THREAD

**Issue by skx** [forkwhilefork/rss2email#13]
It seems like some of your changes aren't really suitable to be merged back in, but I liked reading your commits and issues.

If you have questions/suggestions that could be more useful then please do let me know.

There have been some changes in the upstream project which you might want to look at.

* e.g. `<p><a href="{{.Link}}">{{.Link}}</a></p>` in the template is broken, because the `=` should be quoted.
  * https://github.com/skx/rss2email/pull/13
* e.g. Also a different approach to use a golang template
  * https://github.com/skx/rss2email/pull/25

Anyway I guess you can compare :)

**Comment by forkwhilefork** [comment]
Oh hey! I didn't get notified for this. Glad you like it :) Your tool wasn't quite what I needed but it helped me a lot in building what I did need.

I will take a look at those issues/the upstream changes and merge them if possible. Thanks!

**Comment by skx** [comment]
No worries; I'll close this issue,but it seemed like the obvious way to get in touch :)
